name: Test
on:
  push:
    branches:
      - develop
jobs:
  publish:
    runs-on: ubuntu-latest 
    steps:
      - name: Publish package to TestPyPI
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/